[package]
name = "node"
version = "0.1.0"
authors = ["haydn dufrene <haydn.dufrene@gmail.com>"]

[dependencies]
env_logger = "^0.5.13"
slog = "^2"
slog_derive = "^0"
substrate-telemetry = { git = "https://github.com/azban/substrate", branch = "fix/telemetry-wait-for-logger"}
