apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash-server
  namespace: {{ namespace }}
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:645604410339:certificate/c11794e8-9035-4151-985a-a128c27b9a90
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-19612552,subnet-20c39859,subnet-3555606f
    alb.ingress.kubernetes.io/security-groups: eks-cluster-test-ingress
    alb.ingress.kubernetes.io/success-codes: "404"
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  - host: dash-server-{{ namespace }}.np-test.net
    http:
      paths:
      - path: /*
        backend:
          serviceName: dash-server
          servicePort: 5000

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash-webui
  namespace: {{ namespace }}
  annotations:
    alb.ingress.kubernetes.io/actions.redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:645604410339:certificate/c11794e8-9035-4151-985a-a128c27b9a90
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80,"HTTPS": 443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-19612552,subnet-20c39859,subnet-3555606f
    alb.ingress.kubernetes.io/security-groups: eks-cluster-test-ingress
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
  # https://github.com/kubernetes-sigs/aws-alb-ingress-controller/issues/487#issuecomment-428262702
  - http:
      paths:
      - backend:
          serviceName: redirect
          servicePort: use-annotation
        path: /*
  - host: dash-webui-{{ namespace }}.np-test.net
    http:
      paths:
      - path: /*
        backend:
          serviceName: dash-webui
          servicePort: 80
