apiVersion: v1
kind: ReplicationController
metadata:
  name: dash-collector
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    app: dash-collector
  template:
    metadata:
      labels:
        app: dash-collector
    spec:
      containers:
      - name: dash-collector
        image: 645604410339.dkr.ecr.us-west-2.amazonaws.com/nearprotocol/dash-collector
        env:
        - name: NEAR_COLLECTOR_NODE_API_HOST
          value: observer
        - name: NEAR_COLLECTOR_NODE_API_PORT
          value: "5000"
        - name: NEAR_COLLECTOR_SERVER_API_HOST
          value: dash-server
        - name: NEAR_COLLECTOR_SERVER_API_PORT
          value: "5000"
      imagePullSecrets:
        - name: awsecr-cred
