apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dash
  namespace: {{ namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # https://github.com/kubernetes/ingress-nginx/issues/1567
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /dashboard-server/
        backend:
          serviceName: dash-server
          servicePort: 5000
      - path: /webui/
        backend:
          serviceName: dash-webui
          servicePort: 80
