apiVersion: v1
kind: ReplicationController
metadata:
  name: dash-server
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    app: dash-server
  template:
    metadata:
      labels:
        app: dash-server
    spec:
      containers:
      - name: dash-server
        image: 645604410339.dkr.ecr.us-west-2.amazonaws.com/nearprotocol/dash-server
        ports:
        - containerPort: 5000
        env:
        - name: NEAR_COLLECTOR_SERVER_REDIS_HOST
          value: dash-redis

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dash-redis
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    app: dash-redis
  template:
    metadata:
      labels:
        app: dash-redis
    spec:
      containers:
      - name: dash-redis
        image: redis:5.0.0-alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: dash-server
  namespace: {{ namespace }}
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: dash-server

---
apiVersion: v1
kind: Service
metadata:
  name: dash-redis
  namespace: {{ namespace }}
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: dash-redis

