apiVersion: v1
kind: ReplicationController
metadata:
  name: dashboard-server
spec:
  replicas: 1
  selector:
    app: dashboard-server
  template:
    metadata:
      labels:
        app: dashboard-server
    spec:
      containers:
      - name: dashboard-server
        image: localhost:5000/near/dash-server
        ports:
        - containerPort: 5000
        env:
        - name: NEAR_COLLECTOR_SERVER_REDIS_HOST
          value: dashboard-redis

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: dashboard-redis
spec:
  replicas: 1
  selector:
    app: dashboard-redis
  template:
    metadata:
      labels:
        app: dashboard-redis
    spec:
      containers:
      - name: dashboard-redis
        image: redis:5.0.0-alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-server
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: dashboard-server

---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: dashboard-redis
