apiVersion: v1
kind: ReplicationController
metadata:
    name: {{ prefix }}-dash-server
spec:
  replicas: 1
  selector:
    app: {{ prefix }}-dash-server
  template:
    metadata:
      labels:
        app: {{ prefix }}-dash-server
    spec:
      containers:
      - name: {{ prefix }}-dash-server
        image: 645604410339.dkr.ecr.us-west-2.amazonaws.com/nearprotocol/dash-server
        ports:
        - containerPort: 5000
        env:
        - name: NEAR_COLLECTOR_SERVER_REDIS_HOST
          value: {{ prefix }}-dash-redis

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: {{ prefix }}-dash-redis
spec:
  replicas: 1
  selector:
    app: {{ prefix }}-dash-redis
  template:
    metadata:
      labels:
        app: {{ prefix }}-dash-redis
    spec:
      containers:
      - name: {{ prefix }}-dash-redis
        image: redis:5.0.0-alpine
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: {{ prefix }}-dash-server
spec:
  clusterIP: None
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: {{ prefix }}-dash-server

---
apiVersion: v1
kind: Service
metadata:
  name: {{ prefix }}-dash-redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: {{ prefix }}-dash-redis

