apiVersion: v1
kind: ReplicationController
metadata:
  name: dash-webui
  namespace: {{ namespace }}
spec:
  replicas: 1
  selector:
    app: dash-webui
  template:
    metadata:
      labels:
        app: dash-webui
    spec:
      containers:
      - name: dash-webui
        image: 645604410339.dkr.ecr.us-west-2.amazonaws.com/nearprotocol/dash-webui
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: awsecr-cred

---
apiVersion: v1
kind: Service
metadata:
  name: dash-webui
  namespace: {{ namespace }}
spec:
  clusterIP: None
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: dash-webui
